# ARTIFACT_PUBLICATION use this constant only once per OS to ensure that
# the artifacts are only published once per OS, e.g. linux, osx and
# windows.
language: go
go:
  - 1.12.5
env:
  global:
    - SHA512_CMD=sha512sum
    - GO111MODULE=on
matrix:
  include:
  - os: linux
    dist: bionic
    env:
      - ARTIFACT_PUBLICATION=true
      - NEXUS_VERSION=3.16.2
      - NEXUS_API_VERSION=v1
  - os: linux
    dist: bionic
    env:
      - ARTIFACT_PUBLICATION=false
      - NEXUS_VERSION=3.9.0
      - NEXUS_API_VERSION=beta
  - os: osx
    env:
      - ARTIFACT_PUBLICATION=true
      - SHA512_CMD="shasum -a 512"
      - NEXUS_VERSION=3.16.2
      - NEXUS_API_VERSION=v1
  - os: windows
    env:
      - ARTIFACT_PUBLICATION=true
      - NEXUS_VERSION=3.16.2
      - NEXUS_API_VERSION=v1
addons:
  sonarcloud:
    organization: 030-github
    token:
      secure: $SONAR_TOKEN
before_script:
  - |
    echo 'n3drPass: admin123' > ${HOME}/.n3dr.yaml
    echo "NEXUS_API_VERSION=${NEXUS_API_VERSION}" > .env
script:
  - diff -u <(echo -n) <(gofmt -d ./)
  - export DELIVERABLE="n3dr-${TRAVIS_OS_NAME}"
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$ARTIFACT_PUBLICATION" ]; then go test -short -cover -v -coverprofile=coverage.txt -covermode=atomic ./...; fi
  - go build -o $DELIVERABLE
  - $SHA512_CMD $DELIVERABLE > ${DELIVERABLE}.sha512.txt
  - chmod +x $DELIVERABLE
  - if [ $TRAVIS_OS_NAME == linux ]; then ./integration-tests.sh $NEXUS_VERSION $NEXUS_API_VERSION ./${DELIVERABLE}; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$ARTIFACT_PUBLICATION" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then sonar-scanner -Dsonar.projectKey=030_n3dr -Dsonar.sources=. -Dsonar.host.url=https://sonarcloud.io -Dsonar.coverage.exclusions=cmd/**,**/*_test.go -Dsonar.go.coverage.reportPaths="coverage.txt"; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$ARTIFACT_PUBLICATION" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then bash <(curl -s https://codecov.io/bash); fi
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - $DELIVERABLE
    - ${DELIVERABLE}.sha512.txt
  skip_cleanup: true
  on:
    tags: true
    condition: $ARTIFACT_PUBLICATION == true
